const express = require('express');
const router = express.Router();
require('dotenv').config();

router.post('/summarize', async (req, res) => {
  const { supervisorName, shiftType, notes, openIssues, wmsAlerts, openTickets } = req.body;

  // Try OpenAI first, fall back to smart mock summary
  if (process.env.OPENAI_API_KEY && process.env.OPENAI_API_KEY !== 'your_openai_api_key_here') {
    try {
      const OpenAI = require('openai');
      const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

      const prompt = `You are AutoHandover, an AI system that generates professional warehouse shift handover reports.

Generate a clear, structured handover summary for the incoming supervisor based on this data:

OUTGOING SUPERVISOR: ${supervisorName}
SHIFT: ${shiftType}
SUPERVISOR NOTES: ${notes}
OPEN ISSUES LOGGED: ${openIssues}
WMS ALERTS: ${wmsAlerts}
OPEN IT TICKETS: ${openTickets}

Write a concise handover summary with:
1. Overall shift status (1-2 sentences)
2. Critical items needing immediate attention
3. WMS/operational items to monitor
4. Open IT tickets to be aware of
5. Recommended first actions for incoming supervisor

Keep it professional, clear and under 300 words.`;

      const completion = await openai.chat.completions.create({
        model: 'gpt-3.5-turbo',
        messages: [{ role: 'user', content: prompt }],
        max_tokens: 400,
        temperature: 0.4,
      });

      return res.json({
        success: true,
        summary: completion.choices[0].message.content,
        source: 'openai'
      });
    } catch (err) {
      console.error('OpenAI error, falling back to mock:', err.message);
    }
  }

  // Smart mock summary when no API key
  const criticalTickets = openTickets.filter(t => t.priority === 'High');
  const summary = `AUTOHANDOVER SHIFT SUMMARY — Generated ${new Date().toLocaleString()}

OUTGOING SUPERVISOR: ${supervisorName} | SHIFT: ${shiftType}

OVERALL STATUS: Shift completed with ${openIssues.length} open item(s) requiring follow-up. ${wmsAlerts.filter(a => a.severity === 'High').length > 0 ? 'HIGH priority WMS alerts are active — immediate attention required.' : 'No critical WMS alerts at time of handover.'}

SUPERVISOR NOTES:
${notes || 'No additional notes provided.'}

CRITICAL ITEMS — ACTION REQUIRED:
${criticalTickets.length > 0 ? criticalTickets.map(t => `• [${t.id}] ${t.subject} — Assigned: ${t.assigned_to}`).join('\n') : '• No critical items outstanding.'}

WMS STATUS:
${wmsAlerts.map(a => `• [${a.severity}] ${a.message}`).join('\n') || '• No active WMS alerts.'}

OPEN IT TICKETS (${openTickets.length}):
${openTickets.map(t => `• [${t.id}] ${t.subject} | Priority: ${t.priority} | Status: ${t.status}`).join('\n') || '• No open tickets.'}

RECOMMENDED FIRST ACTIONS:
• Verify Zone B conveyor belt status with maintenance team
• Check on Rush order ORD-20240117 (Target Express) — not yet started
• Review open ticket TKT-1035 (LP-03 label printer) for assignment
• Confirm WMS session timeout fix (TKT-1039) is working

This summary was generated by AutoHandover AI. Please review and confirm accuracy before acknowledging.`;

  res.json({ success: true, summary, source: 'mock' });
});

module.exports = router;
